spring:
    application:
        name: spring-cloud-eureka-server
server:
    port: 8888
eureka:
    instance:
        hostname: 10.1.14.39
        #prefer-ip-address: true
    client:
        registerWithEureka: false
        fetchRegistry: false
        serviceUrl:
            defaultZone: http://10.1.14.39:8888/eureka/